### ISSUE TITLE
Add Game Type column to Games

### ISSUE THREAD

**Issue by jkeena88** [Spartan97/JCS#10]
I know you said bowl games aren't flagged in Sports Reference, but I would like to have this included in our data set even if I have to do it manually.

Rather than a flag I think it should actually be an Int for Game Type, e.g.:
1 = regular season
2 = bowl (non playoff/championship)
3 = playoffs (non championship)
4 = championship
...

**Comment by Spartan97** [comment]
Do you think we could combine this with neutral site flag?
0/1/2 = regular season home/away/neutral
3 = bowl
4 = playoff
5 = championship

Any downside to this or limitation we force upon ourselves?

**Comment by jkeena88** [comment]
First, I don't think home/away make sense since every record is both home AND away the way the rest of the data is structured. Plus I can determine that by the home/away team id. But it could work to do 0/1 = regular season non-neutral/neutral.

Second, there's still a small issue in that bowl games (and theoretically playoff games in the future) can happen in a team's home stadium. It might still be more of a neutral site game than usual but I'd like to be able to identify when this happens (which I could do if it was marked as a non-neutral bowl game using 2 separate columns).

Honestly either way is going to be 99.9% accurate and easy to work with, but I'd probably prefer separate columns for neutral and game type.

**Comment by Spartan97** [comment]
Got it. What should I do for conference championships? Do those fall under championship? Or is that another value we need.

**Comment by jkeena88** [comment]
Ooh good catch. I'd add another value. So like:
0 = regular season
1 = conference championship
2 = bowl
3 = playoffs
4 = national championship

**Comment by Spartan97** [comment]
Thoughts about overseas showcases (Dublin, Australia, etc)? Just handle those like any other neutral site?

**Comment by jkeena88** [comment]
Yeah I say just mark it neutral site. Unless/until we get into location data then it's all just gray area besides home/away/neutral.

**Comment by Spartan97** [comment]
Current plan:

1) Mark all games as regular season
2) CCGs
	- Any game after Dec. 1st (except Army vs Navy)
		- ACC 2005-2016
		- Big 10 after 2011
		- Big 12 from 1996-2010
		- Pac 12 after 2011
		- SEC 1992-2016

		- AAC 2015-2016
		- Conf USA 2005-2016
		- MAC 1997-2016
		- Mountain West 2013-2016
		- WAC 1996-1998

		- Big East (NONE)
		- Sun Belt (NONE)
3) Bowl Games
	- Any game after Army-Navy?
        - Not sure how to handle these as dates aren't fixed.
4) Semifinal/Playoff
	- Manually mark 2014-2016
5) NCG
	- Manually mark 1998-2016

**Comment by jkeena88** [comment]
Finished updating game type through 2017-18 season. Will need to keep updating every year. There might be a few mistakes since going back 40 years there is some overlap between the day of the month when the regular season ends some years and the day of the month when the bowls start other years. I was pretty careful, but should double check later.
