### ISSUE TITLE
Backfill penalty data

### ISSUE THREAD

**Issue by jkeena88** [Spartan97/JCS#5]

**Comment by Spartan97** [comment]
This shouldn't be too hard - at least to 2000. Sports-reference has the data, just a matter of adding to existing rows and not overriding them.

**Comment by Spartan97** [comment]
Got some code up and running for this... it's gonna take a while to run though because it has to open/parse every boxscore again. Running the 2014 stuff overnight. Hopefully it'll be good to go in the morning, then I can run the rest of it tomorrow during the day.

**Comment by Spartan97** [comment]
Note to self:
- Missing Pen/FirstDown data for 2000-2012
- Missing bowlgames from 2000-2012
- DO NOT overwrite existing data, as new site is missing a lot of stuff from FCS-FBS games.

**Comment by Spartan97** [comment]
Mostly done, have some extraneous games to fill out though.
