### ISSUE TITLE
Backfill data prior to 2000

### ISSUE THREAD

**Issue by jkeena88** [Spartan97/JCS#6]
My other source I mentioned actually doesn't have box scores either so it's not any more useful than Sport Reference. If you still want to fill in data back to 18-whenever that's cool, and we can just leave the missing info Null (or 0 or something if you don't allow Null values and don't want to change that).

**Comment by Spartan97** [comment]
Currently it's just blank/nonexistent. So I guess that probably comes out as NULL. Not 100% sure.

I'm not sure about backfilling to the 1800s, but I'll definitely get it as far back as 1978 if we want to call that our arbitrary start date. Unless you think 2000 is a better arbitrary date (evolution of the game and all that jazz).

**Comment by Spartan97** [comment]
This one also kinda goes hand in hand with penalty backfill, so I'll probably knock this off sooner rather than later.

**Comment by jkeena88** [comment]
1978 should be good. If I can still make it run well enough without the missing data I can actually see if the model doesn't work as well decades ago, but it would still be nice to have the data there just in case.

**Comment by Spartan97** [comment]
DONE!
